default: gemma3_local
llms:
  phi4_docker:
    provider: ollama
    model: "phi4"
    api_base: "http://host.docker.internal:11434/"
  gemma3_docker:
    provider: ollama
    model: "gemma3:1b"
    api_base: "http://host.docker.internal:11434/"
  phi4_local:
    provider: ollama
    model: "phi4"
    api_base: "http://localhost:11434/"
  gemma3_local:
    provider: ollama
    model: "gemma3:1b"
    api_base: "http://localhost:11434/"

  gemini_2_0_flash:
    provider: gemini
    model: "gemini-2.0-flash"
    api_key_env: "GEMINI_API_KEY"
  gpt_4o_mini:
    provider: openai
    model: gpt-4o-mini
    api_key_env: "OPENAI_API_KEY"

